"""Image-gallery R2 uploader for the Nerra Network.

Phase 1 of the gallery feature (see ``docs/gallery_storage.md``). Each
image generated by the pipeline (today: Grok Imagine for the YouTube
long-form + Shorts slideshow on Tesla Shorts Time and Models & Agents
for Beginners) is uploaded to a separate R2 bucket — ``nerra-gallery``
by default — together with:

  * A downscaled, watermarked WebP thumbnail (max 800 px on the long
    edge) for public browsing.
  * A JSON sidecar describing the image's provenance (prompt, model,
    episode, license, etc.).

Layout in the bucket::

    {show-slug}/{YYYY-MM-DD}/{episode-id}/{image-id}.{ext}
    {show-slug}/{YYYY-MM-DD}/{episode-id}/{image-id}.thumb.webp
    {show-slug}/{YYYY-MM-DD}/{episode-id}/{image-id}.json

``image-id`` is the first 12 hex characters of the SHA-256 of the
original bytes — so re-runs against the same image bytes are idempotent
(same key, same object).

Authentication reuses the existing R2 account credentials
(``R2_ENDPOINT_URL`` / ``R2_ACCESS_KEY_ID`` / ``R2_SECRET_ACCESS_KEY``).
Bucket name + public base URL come from gallery-specific env vars so
the gallery doesn't share a namespace with the audio bucket.

Failure mode: best-effort. Every call returns ``None`` on missing
credentials, R2 errors, or thumbnail failures, and logs the cause —
the calling pipeline must treat a ``None`` return as "gallery wasn't
updated, video publish continues".
"""

from __future__ import annotations

import hashlib
import io
import json
import logging
import os
import tempfile
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from engine.storage import upload_to_r2

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

LICENSE_DEFAULT = "CC BY-SA 4.0"
LICENSE_URL_DEFAULT = "https://creativecommons.org/licenses/by-sa/4.0/"
ATTRIBUTION_DEFAULT = "Nerra Network"

THUMBNAIL_MAX_EDGE_PX = 800
THUMBNAIL_FORMAT = "webp"
THUMBNAIL_QUALITY = 85

WATERMARK_TEXT = "nerranetwork.com"

_CONTENT_TYPES = {
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
    "gif": "image/gif",
}

_FONT_CANDIDATES = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf",
    "/Library/Fonts/Arial Bold.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
    "C:\\Windows\\Fonts\\arialbd.ttf",
)


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class GalleryConfig:
    """R2 configuration for the gallery bucket.

    Distinct from ``engine.config.StorageConfig`` because the gallery
    bucket is per-network (not per-show) — every show writes to the
    same bucket so the network-wide gallery page can browse everything.
    """

    bucket: str = ""
    endpoint_url: str = ""
    access_key: str = ""
    secret_key: str = ""
    public_base_url: str = ""

    @property
    def is_configured(self) -> bool:
        return bool(
            self.bucket and self.endpoint_url and self.access_key and self.secret_key
        )


@dataclass
class ImageMetadata:
    """Sidecar metadata describing one gallery image.

    Field set matches the schema in the project spec exactly. Anything
    optional defaults to a safe empty value so the JSON sidecar always
    carries the full key set (consumers can rely on every key being
    present even if its value is empty).
    """

    image_id: str
    show_slug: str
    show_name: str
    episode_id: str
    episode_title: str
    episode_date: str
    prompt: str = ""
    model: str = ""
    generated_at: str = ""
    intended_use: str = "segment_card"  # thumbnail | segment_card | social | other
    width: int = 0
    height: int = 0
    format: str = ""
    file_size: int = 0
    caption: str = ""
    tags: List[str] = field(default_factory=list)
    license: str = LICENSE_DEFAULT
    license_url: str = LICENSE_URL_DEFAULT
    attribution: str = ATTRIBUTION_DEFAULT
    youtube_video_id: str = ""

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False, sort_keys=True)


@dataclass
class UploadResult:
    """URLs of the three uploaded objects + the chosen image_id."""

    image_id: str
    original_url: str
    thumbnail_url: str
    sidecar_url: str
    original_key: str
    thumbnail_key: str
    sidecar_key: str


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def gallery_config_from_env() -> GalleryConfig:
    """Build a ``GalleryConfig`` from environment variables.

    Reuses the existing R2 account credentials (same env vars the audio
    pipeline reads). The bucket name + public base URL are
    gallery-specific so we never accidentally mix gallery objects into
    the audio bucket.
    """
    return GalleryConfig(
        bucket=os.getenv("R2_GALLERY_BUCKET", "nerra-gallery").strip(),
        endpoint_url=os.getenv("R2_ENDPOINT_URL", "").strip(),
        access_key=os.getenv("R2_ACCESS_KEY_ID", "").strip(),
        secret_key=os.getenv("R2_SECRET_ACCESS_KEY", "").strip(),
        public_base_url=os.getenv("R2_GALLERY_PUBLIC_BASE_URL", "").strip(),
    )


def compute_image_id(image_bytes: bytes) -> str:
    """Deterministic 12-char content hash, used as the image's R2 stem."""
    return hashlib.sha256(image_bytes).hexdigest()[:12]


def _ext_for_format(image_format: str) -> str:
    fmt = (image_format or "").lower().lstrip(".")
    if fmt in ("jpg", "jpeg"):
        return "jpeg"
    return fmt or "jpeg"


def _content_type_for(ext: str) -> str:
    return _CONTENT_TYPES.get(ext.lower().lstrip("."), "application/octet-stream")


def _load_font(size: int):
    """Reuse the same font-candidate chain other modules use.

    Inlined rather than imported from ``engine.publisher`` so this
    module stays import-light (publisher pulls in feedgen / boto3 /
    tweepy via its own helpers).
    """
    from PIL import ImageFont

    for candidate in _FONT_CANDIDATES:
        if Path(candidate).exists():
            try:
                return ImageFont.truetype(candidate, size)
            except (IOError, OSError):
                continue
    return ImageFont.load_default()


def _apply_watermark(img):
    """Stamp a subtle bottom-right watermark on a Pillow image (RGB).

    Operates on a copy — caller's image is untouched. Size scales with
    the image's long edge so the mark stays legible at any thumbnail
    dimension. Translucent layer composited via ``alpha_composite``
    so we don't have to flatten the source image's alpha channel.
    """
    from PIL import Image, ImageDraw

    base = img.convert("RGBA")
    width, height = base.size
    long_edge = max(width, height)

    # 2.5% of the long edge → ~20 px at 800 px wide. Floor of 12 keeps
    # text legible on small previews; ceiling of 28 keeps it subtle on
    # larger images.
    font_size = max(12, min(28, int(long_edge * 0.025)))
    font = _load_font(font_size)

    overlay = Image.new("RGBA", base.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    try:
        bbox = draw.textbbox((0, 0), WATERMARK_TEXT, font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]
    except AttributeError:
        # PIL < 8.0 (we require >=10 but be defensive).
        text_w, text_h = draw.textsize(WATERMARK_TEXT, font=font)

    pad = max(8, int(font_size * 0.5))
    x = width - text_w - pad
    y = height - text_h - pad - max(2, font_size // 4)

    # Soft shadow first so the mark stays readable over light / dark
    # backgrounds. Both layers at low alpha — "subtle corner mark".
    draw.text((x + 1, y + 1), WATERMARK_TEXT, font=font, fill=(0, 0, 0, 110))
    draw.text((x, y), WATERMARK_TEXT, font=font, fill=(255, 255, 255, 160))

    return Image.alpha_composite(base, overlay).convert("RGB")


def make_thumbnail(
    image_bytes: bytes,
    *,
    max_edge: int = THUMBNAIL_MAX_EDGE_PX,
    watermark: bool = True,
) -> bytes:
    """Downscale to ``max_edge`` on the long side and encode as WebP.

    Always re-encodes (not a passthrough) even if the source is already
    smaller — keeps the watermark application uniform and the bucket
    format stable. WebP at quality 85 lands around 40–70 KB per
    thumbnail for typical Grok Imagine output, which is plenty for
    gallery previews.
    """
    from PIL import Image

    with Image.open(io.BytesIO(image_bytes)) as src:
        src.load()
        img = src.convert("RGB")

    width, height = img.size
    long_edge = max(width, height)
    if long_edge > max_edge:
        scale = max_edge / float(long_edge)
        new_size = (max(1, int(width * scale)), max(1, int(height * scale)))
        img = img.resize(new_size, Image.LANCZOS)

    if watermark:
        img = _apply_watermark(img)

    buf = io.BytesIO()
    img.save(buf, format="WEBP", quality=THUMBNAIL_QUALITY, method=6)
    return buf.getvalue()


def probe_image(image_bytes: bytes) -> tuple[int, int, str]:
    """Return ``(width, height, format_ext)`` for the image bytes.

    Format is normalised to a lowercase extension without the dot
    (``"jpeg"`` / ``"png"`` / ``"webp"``). Defaults to ``"jpeg"`` if
    Pillow can't determine the format — matches the Grok Imagine path
    which always returns JPEG bytes today.
    """
    from PIL import Image

    with Image.open(io.BytesIO(image_bytes)) as src:
        src.load()
        width, height = src.size
        fmt = (src.format or "JPEG").lower()
    if fmt == "jpg":
        fmt = "jpeg"
    return width, height, fmt


def _build_keys(metadata: ImageMetadata, ext: str) -> tuple[str, str, str]:
    """Build the R2 object keys for original / thumbnail / sidecar."""
    prefix = f"{metadata.show_slug}/{metadata.episode_date}/{metadata.episode_id}"
    stem = metadata.image_id
    return (
        f"{prefix}/{stem}.{ext}",
        f"{prefix}/{stem}.thumb.webp",
        f"{prefix}/{stem}.json",
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def upload_image(
    image_bytes: bytes,
    metadata: ImageMetadata,
    *,
    gallery_config: Optional[GalleryConfig] = None,
) -> Optional[UploadResult]:
    """Upload one image (original + thumbnail + sidecar) to R2.

    Returns ``None`` (and logs) when gallery credentials are missing or
    when the R2 upload of any of the three objects fails. The caller
    must treat ``None`` as a soft failure that doesn't block the
    surrounding pipeline.

    Mutates ``metadata`` in place to fill in fields the caller may have
    left blank: ``image_id`` (content hash), ``width`` / ``height`` /
    ``format`` (probed from the bytes), ``file_size``, ``generated_at``
    (UTC, RFC 3339). All caller-supplied non-empty values are
    preserved.
    """
    config = gallery_config or gallery_config_from_env()
    if not config.is_configured:
        logger.info("Gallery R2 not configured — skipping upload")
        return None

    if not image_bytes:
        logger.warning("upload_image called with empty bytes — skipping")
        return None

    try:
        width, height, probed_format = probe_image(image_bytes)
    except Exception as exc:  # noqa: BLE001 — corrupt bytes = soft fail
        logger.warning("Pillow failed to probe image bytes: %s", exc)
        return None

    if not metadata.image_id:
        metadata.image_id = compute_image_id(image_bytes)
    if not metadata.width:
        metadata.width = width
    if not metadata.height:
        metadata.height = height
    if not metadata.format:
        metadata.format = probed_format
    if not metadata.file_size:
        metadata.file_size = len(image_bytes)
    if not metadata.generated_at:
        metadata.generated_at = datetime.now(timezone.utc).isoformat(
            timespec="seconds"
        )
    if not metadata.license:
        metadata.license = LICENSE_DEFAULT
    if not metadata.license_url:
        metadata.license_url = LICENSE_URL_DEFAULT
    if not metadata.attribution:
        metadata.attribution = ATTRIBUTION_DEFAULT

    ext = _ext_for_format(metadata.format)
    original_key, thumbnail_key, sidecar_key = _build_keys(metadata, ext)

    try:
        thumbnail_bytes = make_thumbnail(image_bytes)
    except Exception as exc:  # noqa: BLE001 — thumbnail failure shouldn't block original
        logger.warning(
            "Thumbnail generation failed for image %s: %s — skipping upload",
            metadata.image_id, exc,
        )
        return None

    sidecar_bytes = metadata.to_json().encode("utf-8")

    with tempfile.TemporaryDirectory(prefix="gallery_upload_") as tmpdir:
        tmp_root = Path(tmpdir)
        original_path = tmp_root / f"{metadata.image_id}.{ext}"
        thumbnail_path = tmp_root / f"{metadata.image_id}.thumb.webp"
        sidecar_path = tmp_root / f"{metadata.image_id}.json"

        original_path.write_bytes(image_bytes)
        thumbnail_path.write_bytes(thumbnail_bytes)
        sidecar_path.write_bytes(sidecar_bytes)

        try:
            original_url = upload_to_r2(
                original_path,
                original_key,
                bucket=config.bucket,
                endpoint_url=config.endpoint_url,
                access_key=config.access_key,
                secret_key=config.secret_key,
                public_base_url=config.public_base_url,
                content_type=_content_type_for(ext),
            )
            thumbnail_url = upload_to_r2(
                thumbnail_path,
                thumbnail_key,
                bucket=config.bucket,
                endpoint_url=config.endpoint_url,
                access_key=config.access_key,
                secret_key=config.secret_key,
                public_base_url=config.public_base_url,
                content_type="image/webp",
            )
            sidecar_url = upload_to_r2(
                sidecar_path,
                sidecar_key,
                bucket=config.bucket,
                endpoint_url=config.endpoint_url,
                access_key=config.access_key,
                secret_key=config.secret_key,
                public_base_url=config.public_base_url,
                content_type="application/json",
            )
        except Exception as exc:  # noqa: BLE001 — log + soft-fail
            logger.error(
                "Gallery R2 upload failed for image %s (%s): %s",
                metadata.image_id, type(exc).__name__, exc,
            )
            return None

    return UploadResult(
        image_id=metadata.image_id,
        original_url=original_url,
        thumbnail_url=thumbnail_url,
        sidecar_url=sidecar_url,
        original_key=original_key,
        thumbnail_key=thumbnail_key,
        sidecar_key=sidecar_key,
    )
