#!/usr/bin/env bash
#
# create_recovery_pr.sh
#
# Last-resort recovery for episode output commits when direct `git push origin main`
# fails repeatedly with GitHub server errors (e.g. "fatal error in commit_refs").
#
# Called from the "Commit and push output" step in .github/workflows/run-show.yml
# only after the 4-attempt rebase/merge loop has been exhausted, and only when
# the local commit for a successful pipeline run already exists.
#
# The script:
#   1. Creates a fresh recovery/<show>-<run_id>-<ts> branch from the current HEAD
#      (which already has the good commit with digests/, transcripts, blog/, etc.)
#   2. Pushes the branch
#   3. Opens a draft PR with a clear title/body explaining what happened and
#      the exact recovery steps for the operator
#   4. Emits a ::warning:: annotation visible in the Actions UI
#
# On success the script exits 0 (the calling job step treats the overall
# "commit phase" as successful because the artifacts are now safe in a PR).
# Only exits 1 if even the recovery branch push itself fails (extremely rare).
#
# Environment variables expected (set by the caller):
#   SHOW      - the show slug (e.g. "unintended_consequences", "tesla")
#   RUN_ID    - the GitHub Actions run ID
#   REPO_URL  - full URL to the repo (for links in the PR body)
#
# The script is intentionally self-contained and has no external deps beyond
# git + gh (both present in GitHub-hosted runners).

set -euo pipefail

SHOW="${SHOW:-unknown}"
RUN_ID="${RUN_ID:-${GITHUB_RUN_ID:-unknown}}"
REPO_URL="${REPO_URL:-https://github.com/Planetterrian/nerranetwork}"

TIMESTAMP=$(date +%s)
RECOVERY_BRANCH="recovery/${SHOW}-${RUN_ID}-${TIMESTAMP}"

echo "=== Recovery PR creation for ${SHOW} (run ${RUN_ID}) ==="
echo "Creating branch: ${RECOVERY_BRANCH}"

git checkout -b "${RECOVERY_BRANCH}"

if ! git push -u origin "${RECOVERY_BRANCH}"; then
  echo "CRITICAL: Recovery branch push failed for ${SHOW}."
  echo "The generated artifacts may be lost when this runner is terminated."
  echo "::error::Recovery branch push failed for ${SHOW}. Manual rescue required from the runner logs or local checkout."
  exit 1
fi

echo "Recovery branch pushed successfully."

# Build the PR body via a temp file (clean, no quoting issues).
BODY_FILE=$(mktemp)
cat > "${BODY_FILE}" <<BODYEOF
Direct push to \`main\` failed repeatedly with a GitHub server-side error ("fatal error in commit_refs") after the pipeline had already produced a successful local commit.

**What is in this PR (all generated by the successful run):**
- \`digests/${SHOW}/\` — episode markdown, full Whisper transcripts (JSON + .txt + _tts.txt), chapters JSON, metrics JSON, credit-usage JSON
- \`blog/${SHOW}/\` — the human-readable blog post HTML
- Any updated RSS feeds, show HTML pages, sitemap.xml, or topic queue state produced by this run

**Why this happened:**
GitHub occasionally returns transient ref-update errors during \`git push\` (especially on larger text commits containing multi-thousand-line transcripts + metrics). The normal 4-attempt rebase/merge retry loop in the workflow was exhausted.

**Operator recovery steps:**
1. Review the files changed in this PR.
2. Merge (or squash-merge) this PR into \`main\`. The episode artifacts are now permanently preserved.
3. The next scheduled (or manual) run of the same show will see the committed outputs and will correctly skip re-generation thanks to deduplication and the topic-queue "already produced" guard.
4. (Optional) If you want perfectly linear history you can reset the recovery branch locally after merge and force-push a clean state — but it is not required.

**Context:**
- Show: ${SHOW}
- Run: ${REPO_URL}/actions/runs/${RUN_ID}
- Original failed push: see the "Commit and push output" step logs in the run above
- Recovery branch: ${RECOVERY_BRANCH}

This mechanism exists so that a successful generation is **never** lost to GitHub push flakiness (the previous failure mode before this guard was entire days of episodes disappearing when a non-critical later step caused the commit step to be skipped).
BODYEOF

echo "Opening draft recovery PR..."

if gh pr create \
  --title "Recovery: ${SHOW} episode outputs (run ${RUN_ID})" \
  --body-file "${BODY_FILE}" \
  --base main \
  --head "${RECOVERY_BRANCH}" \
  --draft; then
  echo "Recovery PR opened successfully."
else
  echo "Warning: gh pr create returned non-zero (may already exist or other transient)."
fi

rm -f "${BODY_FILE}"

echo "::warning::Recovery PR created for ${SHOW} (run ${RUN_ID}). Merge it to permanently save the episode artifacts that would otherwise have been lost."

# Success from the perspective of "data is preserved".
exit 0
